### ISSUE TITLE
Add test for RandomNVector

### ISSUE THREAD

**Issue by olafmersmann** [olafmersmann/lhc-generator#1]
Check that elements are indeed in increasing order.

Look into [GTest](https://github.com/google/googletest).

**Comment by olafmersmann** [comment]
Or try out [Catch2](https://github.com/catchorg/Catch2).

**Comment by konsdt** [comment]
Used Gtest to check if elements are in increasing order. Catch2 seems to be awaiting version3 update and its tutorial is therefore not up to date which complicates usability. Also not sure wether there is a meson wrap for catch2.
